export const UPDATE_INDIVIDUAL_OPTION = "UPDATE_INDIVIDUAL_OPTION";
export const UPDATE_ARRAY_FILTERING_OPTIONS = "UPDATE_ARRAY_FILTERING_OPTIONS";
export const UPDATE_CARD_SIDE = "UPDATE_CARD_SIDE";
export const GET_NEXT_CARD = "GET_NEXT_CARD";
export const GET_PREVIOUS_CARD = "GET_PREVIOUS_CARD";
export const RESET_CARD_INDEX = "RESET_CARD_INDEX";
